-- Usuário admin
INSERT INTO USUARIO (NOME, LOGIN, SENHA, PERFIL) VALUES ('Administrador', 'admin', '123', 'ADMIN');
COMMIT;

-- Material inicial
INSERT INTO MATERIAL (NOME, QUANTIDADE, UNIDADE, PONTO_REPOSICAO) VALUES ('Água', 100.00, 'ml', 20.00);
COMMIT;
