INSERT INTO USUARIO (NOME, LOGIN, SENHA, PERFIL)
VALUES ('Administrador', 'admin', '1234', 'ADMIN');

INSERT INTO USUARIO (NOME, LOGIN, SENHA, PERFIL)
VALUES ('Operador', 'oper', '1234', 'OPERADOR');

-- Materiais iniciais
INSERT INTO MATERIAL (NOME, QUANTIDADE, UNIDADE, PONTO_REPOSICAO)
VALUES ('Reagente A', 100, 'ml', 20);

INSERT INTO MATERIAL (NOME, QUANTIDADE, UNIDADE, PONTO_REPOSICAO)
VALUES ('Pipeta Descartável', 500, 'un', 100);

INSERT INTO MATERIAL (NOME, QUANTIDADE, UNIDADE, PONTO_REPOSICAO)
VALUES ('Tubo de Ensaio', 200, 'un', 50);

COMMIT;
